"""empty message

Revision ID: 3b852b693e6c
Revises: d7a0c6606cb9
Create Date: 2017-08-31 10:59:06.140000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3b852b693e6c'
down_revision = 'd7a0c6606cb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=100), nullable=False))
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
